# Generated by Django 5.2.16 on 2026-08-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_alter_profissional_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]
