# Generated by Django 5.2.16 on 2026-09-22 23:41

import profissionais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_profissional_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=profissionais.models.caminho_foto_perfil),
        ),
    ]
