# Generated by Django 5.2.16 on 2026-09-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0004_alter_profissional_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('codigo_hash', models.CharField(max_length=64)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de verificação de e-mail',
                'verbose_name_plural': 'Códigos de verificação de e-mail',
            },
        ),
    ]
