# Generated by Django 5.2.16 on 2026-08-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('clinicas', '0002_clinica_ativo_clinica_profissional_and_more'),
        ('pacientes', '0001_initial'),
        ('profissionais', '0002_alter_profissional_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CA'), _negated=True), fields=('paciente', 'data', 'hora_inicio'), name='paciente_sem_conflito_agendamento'),
        ),
    ]
