# Generated by Django 5.2.16 on 2026-08-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_paciente_sem_conflito_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='eh_gratuito',
        ),
    ]
