# Generated by Django 5.2.16 on 2026-08-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agendamento_eh_gratuito'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='grupo_recorrencia',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
