# Generated by Django 5.2.16 on 2026-09-18 00:20

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('agenda', '0004_agendamento_grupo_recorrencia'),
        ('clinicas', '0002_clinica_ativo_clinica_profissional_and_more'),
        ('pacientes', '0003_alter_paciente_cpf_alter_paciente_email_and_more'),
        ('profissionais', '0003_profissional_foto'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='agendamento',
            index=models.Index(fields=['data'], name='agenda_agendamento_data_idx'),
        ),
    ]
