# Generated by Django 5.2.16 on 2026-07-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
        ('profissionais', '0002_alter_profissional_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='valor_por_atendimento',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VinculoClinica',
        ),
    ]
